site_name: Quant Journey Blog
site_description: "QuantJourney with Code is a blog about quantitative finance, data science, and programming."
site_author: Jakub Polec
site_url: http://quantjourney.blog/

# Theme
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.top
  - navigation.indexes
  - navigation.footer
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - toc.integrate
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
- Getting Started:
  - Overview: index.md
  - Start: documentation.md
